### ISSUE TITLE
tcks output contains empty tck files

### ISSUE THREAD

**Issue by soichih** [FBK-NILab/app-classifyber-segmentation#2]
I just ran this App on all supported IDs

> 21,22,23,24,25,26,27,28,29,30,32,33,35,36,38,39,40,41,42,43,44,45

The output looks great, and all tracts has non-0 number of fibers in them.

![image](https://user-images.githubusercontent.com/923896/81069900-85e53200-8eb0-11ea-8ae0-1264aa8ba5b8.png)

However, when I looked at the tcks output, I've noticed that only a few of them actually have fibers in them, and most of them are empty (size is 75bytes)

![image](https://user-images.githubusercontent.com/923896/81070007-a7461e00-8eb0-11ea-84a2-607bcf948dc6.png)

**Comment by giulia-berto** [comment]
Thank you for noticing it, I guess it has to do with the recent change I made to the code as a consequence of the discussion on the wmc-validator. I will fix that!

**Comment by giulia-berto** [comment]
Fixed.
