### ISSUE TITLE
wmc output using deprecated output mode

### ISSUE THREAD

**Issue by soichih** [FBK-NILab/app-classifyber-segmentation#3]
This App is using a deprecated output mode for `wmc` output.

![image](https://user-images.githubusercontent.com/923896/81191357-f1013800-8f86-11ea-8f8a-67f37c06c932.png)

We should not be using this anymore, as it is deprecated. Please make the following update.

1) Instead of using the ID "5". Update it to something like "wmc".
2) Update the App so that wmc output will be stored under "wmc" subdirectory.
3) Uncheck the "(DEPRECATED) ignore output directory" check box.

**Comment by giulia-berto** [comment]
Thank you, done it!
